on: [push]

jobs:
  build:
    name: Run build script on MacOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run build script
        run: ./build.sh

      - uses: actions/upload-artifact@v2
        with:
          name: crossover
          path: ./
